# Generated by Django 3.2.12 on 2022-03-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='logout_time',
        ),
    ]
