# Generated by Django 3.2.12 on 2022-03-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_auto_20220305_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='acntexpensest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.CharField(max_length=100)),
                ('payacnt', models.CharField(max_length=200)),
                ('paymethod', models.CharField(max_length=100)),
                ('paydate', models.CharField(max_length=100)),
                ('refno', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('total', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_fee', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user_registration',
            name='account_no',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='bank_branch',
            field=models.CharField(default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='bank_name',
            field=models.CharField(default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='ifsc',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='payment_balance',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='payment_status',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='total_pay',
            field=models.IntegerField(default='0'),
        ),
        migrations.CreateModel(
            name='paymentlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_pay', models.IntegerField(default='0')),
                ('amount_date', models.DateField(blank=True, null=True)),
                ('current_date', models.DateField(blank=True, null=True)),
                ('amount_status', models.CharField(max_length=200, null=True)),
                ('amount_downlod', models.FileField(blank=True, null=True, upload_to='images/')),
                ('balance_amt', models.IntegerField(default='0')),
                ('course', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total', to='base_app.course')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userpay', to='base_app.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='acntspayslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.IntegerField()),
                ('eno', models.CharField(max_length=100)),
                ('hra', models.IntegerField()),
                ('conveyns', models.CharField(max_length=100)),
                ('tax', models.IntegerField()),
                ('incentives', models.IntegerField()),
                ('fromdate', models.DateField(blank=True, null=True)),
                ('todate', models.DateField(blank=True, null=True)),
                ('taxengine', models.CharField(max_length=100)),
                ('incometax', models.IntegerField()),
                ('uan', models.CharField(max_length=100)),
                ('pf', models.IntegerField()),
                ('esi', models.CharField(max_length=100)),
                ('pro', models.CharField(max_length=100)),
                ('leavesno', models.IntegerField()),
                ('pf_tax', models.IntegerField()),
                ('delay', models.IntegerField()),
                ('basictype', models.CharField(default='', max_length=255)),
                ('hratype', models.CharField(default='', max_length=255)),
                ('contype', models.CharField(default='', max_length=255)),
                ('protype', models.CharField(default='', max_length=255)),
                ('instype', models.CharField(default='', max_length=255)),
                ('deltype', models.CharField(default='', max_length=255)),
                ('leatype', models.CharField(default='', max_length=255)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dept', to='base_app.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='desic', to='base_app.designation')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='base_app.user_registration')),
            ],
        ),
        migrations.AddField(
            model_name='user_registration',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_name', to='base_app.course'),
        ),
    ]
