# Generated by Django 3.2.12 on 2022-03-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_auto_20220310_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='acntspayslip',
            name='esitype',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='acntspayslip',
            name='pftype',
            field=models.CharField(default='', max_length=255),
        ),
    ]
