# Generated by Django 3.2.12 on 2022-03-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_auto_20220314_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='hrmanager',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
