# Generated by Django 4.0.2 on 2022-03-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_user_registration_hrmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_registration',
            name='email',
            field=models.EmailField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='branch_registration',
            name='logo',
            field=models.FileField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='branch_registration',
            name='mobile',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
